apiVersion: apps/v1
kind: Deployment
metadata:
  name: jussun-api
  namespace: prod
  labels:
    app: jussun-api
spec:
  selector:
    matchLabels:
      app: jussun-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jussun-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: jussun-api
          image: ghcr.io/champalab/jussun-api:bf79c4d1bd2ff793e542a54347a107e5114699fc
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          livenessProbe:
            tcpSocket:
              port: 1188
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1188
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: jussun-api-config
            - secretRef:
                name: database-jussun-api
            - secretRef:
                name: jwt-secret
          ports:
            - containerPort: 1188
              name: http
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: vol-jussun-api
              mountPath: /app/logs
              subPath: vol-jussun-api/logs-prod
            - name: vol-jussun-api
              mountPath: /app/uploads
              subPath: vol-jussun-api/uploads-prod
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: vol-jussun-api
          nfs:
            path: /mnt/share
            server: gfs-01
      restartPolicy: Always
