apiVersion: apps/v1
kind: Deployment
metadata:
  name: jussun-api
  namespace: prod
  labels:
    app: jussun-api
spec:
  selector:
    matchLabels:
      app: jussun-api
  # replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jussun-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: jussun-api
          image: ghcr.io/champalab/jussun-api:36dac244ffb38e9a2eee2a3e0e27eba336e262d5
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1048Mi
          livenessProbe:
            tcpSocket:
              port: 1188
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1188
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: jussun-api-config
            # - secretRef:
            #     name: database-jussun-api
            # - secretRef:
            #     name: jwt-secret
          ports:
            - containerPort: 1188
              name: http
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: vol-jussun-api
              mountPath: /app/logs
              subPath: vol-jussun-api/logs
            - name: vol-jussun-api
              mountPath: /app/uploads
              subPath: vol-jussun-api/uploads
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: vol-jussun-api
          nfs:
            path: /mnt/share
            server: gfs-01
      restartPolicy: Always
