apiVersion: apps/v1
kind: Deployment
metadata:
  name: jussun-api
  namespace: production
  labels:
    app: jussun-api
spec:
  selector:
    matchLabels:
      app: jussun-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jussun-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: jussun-api
          image: ghcr.io/champalab/jussun-api:d4ced00dfde18134abb4ed7c8fd8df2248fb3862
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          livenessProbe:
            tcpSocket:
              port: 1133
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1133
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: jussun-api-config
            - secretRef:
                name: database-parking-hub
            - secretRef:
                name: jwt-secret
          ports:
            - containerPort: 1133
              name: http
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            # - name: vol-jussun-prod
            #   mountPath: /app/logs
            #   subPath: vol-jussun-prod/logs
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: vol-jussun-prod
          # nfs:
          #   path: /mnt/vol-k8s
          #   server: gfs-01
      restartPolicy: Always
