apiVersion: v1
kind: Service
metadata:
  name: jussun-api-service
  namespace: production
spec:
  selector:
    app: jussun-api
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: jussun-api-port
      protocol: TCP
      port: 80
      targetPort: 1188
      nodePort: 30001
