name: Node.js CI

on:
    push:
        branches: ['main']
        paths-ignore:
            - 'servers/actions-runner/JUTSUN-API/jutsun-node/jutsun-node/uploads/**'
    pull_request:
        branches: ['main']
        paths-ignore:
            - 'servers/actions-runner/JUTSUN-API/jutsun-node/jutsun-node/uploads/**'

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - name: Change Directory and Run Commands
              run: |
                  cd servers/actions-runner/JUTSUN-API/jutsun-node/jutsun-node/
                  rm -rf .env
                  cp -rp .env.prod .env
                  yarn
                  yarn db
                  yarn build
            - name: Manage PM2 Process
              run: |
                  cd servers/actions-runner/JUTSUN-API/jutsun-node/jutsun-node/
                  if pm2 list | grep -q JUTSUN-API; then
                    echo "Process JUTSUN-API already running. Restarting..."
                    pm2 restart JUTSUN-API
                  else
                    echo "Starting JUTSUN-API..."
                    pm2 start ./dist/index.js --name JUTSUN-API
                  fi
            - run: pm2 save
            - run: pm2 startup
            - run: pm2 save
            - name: Reload NGINX
              run: sudo service nginx reload
