name: Node.js CI

on:
    push:
        branches: ['develop']
    pull_request:
        branches: ['develop']

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: rm -rf .env
            - run: cp -rp .env.dev .env
            - run: yarn
            - run: yarn build
            - run: pm2 start ./dist/index.js --name JUTSUN-API
            - run: pm2 restart JUTSUN-API
            - run: sudo pm2 save
            - run: sudo pm2 startup
            - run: sudo pm2 save
            - run: sudo service nginx reload
